id: Cnn10-32k-T-seeded
_target_: noisegap.models.SeededCnn10
initialization_seed: ${seed}
transfer: https://zenodo.org/records/3987831/files/Cnn10_mAP%3D0.380.pth

transform:
  type: grayscale
  base:
    - autrainer.transforms.Normalize: null
